# This file was generated by GoReleaser. DO NOT EDIT.
cask "gqlhash-proxy" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "3503a0442761ed0057f9b97c4456a0a6df95126ebae035b2ea016055ad7fa7b2"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8fbd4fc20426b676a5eeb6863941abd5d3a10be720e3b8b4e0111b16bd799eee"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "790b1c328f4bacb1cde8d90e186fc68f3e39f81c162abf90616b3d21a00d18f0"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "efb47bc2bb9fa79bf6fee66204dffac1f7219fde55b7443325db9682adac6900"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Linux_arm64.tar.gz"
    end
  end

  name "gqlhash-proxy"
  desc "Serves an allowlist of GraphQL documents in front of an API"
  homepage "https://github.com/romshark/gqlhash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gqlhash-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gqlhash-proxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Upgrading from v1: gqlhash now hashes with SHA-256 by default where v1 used
    SHA-1, some documents hash differently under any function, and a few v1
    accepted are now refused. Anything holding a stored hash has to rebuild it;
    -hash sha1 keeps what v1 printed. What changed:
    https://github.com/romshark/gqlhash/blob/main/MIGRATION.md
  EOS
end
