# This file was generated by GoReleaser. DO NOT EDIT.
cask "gqlhash" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "49516367eb65d84dfcb9616f233f5d4377ff796d0b0ea80993f80a482b1d5acb"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b5a9e06fcacf84a8221cf3c7891de0a876008f20b341d72027c82d7ed2871436"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "62a6c176a3bd2f6dd7897af0d43638eadda8aab38b4f8c030e296575e2ab3ce1"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5025655c37233238c6c22f9e3c974b022934eb82ec505ab7dd55de91c0ecc193"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Linux_arm64.tar.gz"
    end
  end

  name "gqlhash"
  desc "Hashes GraphQL executable documents, ignoring formatting"
  homepage "https://github.com/romshark/gqlhash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gqlhash"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gqlhash"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    v1 shipped as a formula and this is a cask. Homebrew replaces neither with
    the other, so if `brew list --formula` still lists gqlhash, run
    `brew uninstall --formula gqlhash` first.

    Upgrading from v1: gqlhash now hashes with SHA-256 by default where v1 used
    SHA-1, some documents hash differently under any function, and a few v1
    accepted are now refused. Anything holding a stored hash has to rebuild it;
    -hash sha1 keeps what v1 printed. What changed:
    https://github.com/romshark/gqlhash/blob/main/MIGRATION.md
  EOS
end
