# This file was generated by GoReleaser. DO NOT EDIT.
cask "gqlhash" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "7f1420c7742a34a76d1bfa2efcde14bbf8183f51df51580b85a988899ae74a9f"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3c381c9e38202ed81cdeb4a0b875660370c00b964e8cc4ab2de47a53d43f54d3"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8bd87caf04b768d273479212058a784711bc44a9a40adcdd94f56a2708fa25ab"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3efa103d198c92a6fdd76b489a75af3e3950a6af8440b61f9029fdd73c080d9d"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Linux_arm64.tar.gz"
    end
  end

  name "gqlhash"
  desc "Hashes GraphQL executable documents, ignoring formatting"
  homepage "https://github.com/romshark/gqlhash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gqlhash"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gqlhash"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    v1 shipped as a formula and this is a cask. Homebrew replaces neither with
    the other, so if `brew list --formula` still lists gqlhash, run
    `brew uninstall --formula gqlhash` first.

    Upgrading from v1: gqlhash now hashes with SHA-256 by default where v1 used
    SHA-1, some documents hash differently under any function, and a few v1
    accepted are now refused. Anything holding a stored hash has to rebuild it;
    -hash sha1 keeps what v1 printed. What changed:
    https://github.com/romshark/gqlhash/blob/main/MIGRATION.md
  EOS
end
