# This file was generated by GoReleaser. DO NOT EDIT.
cask "gqlhash" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "60ad22a1963e84ec7a6ddc3a762c98a050cf1fcb4e574ee193f1d9e9f2d5ac0b"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "41f9ae9be73fa9cfe04358dfc9984349b72b2678a32236307bf5331a8316f787"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7dca14882b3f1ce8e8cd709fca40c6fc2ece19dc1491c22ff9719cb2a4fdc26"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "52f15bb2df60f65415be8a4fb8e59e227815b6e842ba67ceaf6f18e432a9aae3"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash_Linux_arm64.tar.gz"
    end
  end

  name "gqlhash"
  desc "Hashes GraphQL executable documents, ignoring formatting"
  homepage "https://github.com/romshark/gqlhash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gqlhash"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gqlhash"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Upgrading from v1: gqlhash now hashes with SHA-256 by default where v1 used
    SHA-1, some documents hash differently under any function, and a few v1
    accepted are now refused. Anything holding a stored hash has to rebuild it;
    -hash sha1 keeps what v1 printed. What changed:
    https://github.com/romshark/gqlhash/blob/main/MIGRATION.md
  EOS
end
