# This file was generated by GoReleaser. DO NOT EDIT.
cask "gqlhash-proxy" do
  version "2.0.1"

  on_macos do
    on_intel do
      sha256 "0623ff3a58bb8d427435f31e95c0929cd7611bd64b8476a4361f1e6cf57e57fc"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "68b4ec0926c551176ba0873b764c6af5dc731e0fb7ba5412792cc313eb3a283f"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7f5af093a5fd16f83f8f431e084a5e63742a5b4c1a41f65edd86c5c5ac6b3704"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "415ba4ca809980e66802b7394dfa36dc8ca5c487e4d8b23b6b8ea7befd811322"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Linux_arm64.tar.gz"
    end
  end

  name "gqlhash-proxy"
  desc "Serves an allowlist of GraphQL documents in front of an API"
  homepage "https://github.com/romshark/gqlhash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gqlhash-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gqlhash-proxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Upgrading from v1: gqlhash now hashes with SHA-256 by default where v1 used
    SHA-1, some documents hash differently under any function, and a few v1
    accepted are now refused. Anything holding a stored hash has to rebuild it;
    -hash sha1 keeps what v1 printed. What changed:
    https://github.com/romshark/gqlhash/blob/main/MIGRATION.md
  EOS
end
