# This file was generated by GoReleaser. DO NOT EDIT.
cask "gqlhash-proxy" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "fde7db719a58a744de213e140cd43185e5fb2e1c80c118a702da15b10be3a7ed"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7a80c237ee90ff77aeee30ba875a8f653686798a2d8fb7c8dc3c709264c24eac"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a02687500fdc9d787a759bd0c2d615ab82bd0d447a347b13a42a1ce7007a8041"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "de139efe6d939e88641d834b2a2cb8b12c17420d4c893bf2fe57b6a93cfc3ee0"
      url "https://github.com/romshark/gqlhash/releases/download/v#{version}/gqlhash-proxy_Linux_arm64.tar.gz"
    end
  end

  name "gqlhash-proxy"
  desc "Serves an allowlist of GraphQL documents in front of an API"
  homepage "https://github.com/romshark/gqlhash"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gqlhash-proxy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gqlhash-proxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Upgrading from v1: gqlhash now hashes with SHA-256 by default where v1 used
    SHA-1, some documents hash differently under any function, and a few v1
    accepted are now refused. Anything holding a stored hash has to rebuild it;
    -hash sha1 keeps what v1 printed. What changed:
    https://github.com/romshark/gqlhash/blob/main/MIGRATION.md
  EOS
end
